# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbf9a3646274ed05458fc55bc5276258d9310b9b18453d5a0bd0ce8235dac017207174f2eae1a3710025d30b9331e1f77b0a058358e7616947f062b0ec1ff48a

test:
  secret_key_base: 0c7744111a5eeaefd36c3673d168693ba0235897c715898d4295d213c72e639a6214ff5eb1ca613be04d103fcbeb6780afc189c994c25663722ad2e6189a3b7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || 'secret' %>
